### ISSUE TITLE
Google sheet megjelenítése HTML oldalon

### ISSUE THREAD

**Issue by lbarjak** [edemo/Lidehouse#4]
Erre egy jQuery modul:
https://github.com/chriszarate/sheetrock

**Comment by krosza** [comment]
Akkor ezzel meg tudjuk azt csinálni, hogy a meteorban majd tetszés szerinti táblákat jelenítünk meg?

**Comment by lbarjak** [comment]
Igen.

**Comment by krosza** [comment]
nem tudnánk ezt vhogy tesztelni? 
pl egy wp oldalt megcsinálni így?
vagy az kidobott munka mert a meteorban minden más?

**Comment by lbarjak** [comment]
Ide tettem egy tesztet, az iframe-ben levő tábla fölött amit látsz, kis táblázat:
http://barjak.net/thaz2/
Ez egy kisméretű kód (CTRL+U megmutatja), betehetjük wp oldalba is.

**Comment by lbarjak** [comment]
Betettem a tesztoldalra a szükséges kódokat, szét kellene tenni a megfelelő helyekre, sajnos egyáltalán nem ismerem a CMS-eket.

**Comment by krosza** [comment]
Hat, en meg azt se tudom mi a cms😊

**Comment by lbarjak** [comment]
Hát pl. a WP :) Ide feltettem a táblát amit kértél:
http://barjak.net/thaz2/

**Comment by krosza** [comment]
igen látom, hogy történik a szinkronizálás?
valahogy eltérnek a listák

**Comment by lbarjak** [comment]
Azért térnek el, mert teszés szerint állíthatjuk be, hány oszlopot milyen sorrendben, melyik szerint és hogyan rendezve ábrázolunk:
            query: "select B,C,D,E,F order by C desc",
// a B,C,D,E,F oszlopokat ábrázolom C szerint rendezve csökkenő sorrendben
            fetchSize: 24
// 24 sor legyen a képernyőn

**Comment by krosza** [comment]
ok, már látom

2017-04-24 10:05 GMT+02:00 Laszlo Barjak <notifications@github.com>:

**Comment by krosza** [comment]
Ezt úgy is meg tudod csinálni, hogy a fejléc fix maradjon és ha több sor van akkor lehet görgetni?

**Comment by lbarjak** [comment]
A szokásos HTML - CSS - JS környezet tudja ezt, először elég csak a fejlécet lekérni egy div-be amit lehet rögzíteni, aztán másik divbe a teljes táblát, ezt lehet scrollozni a ha nem fér ki, a Sheetrock fetchSize ugyan csak egy paraméterű, de láthatatlanná lehet tenni a felesleges sorokat. (Vagy akár módosítani is lehet a fetchSize metódust.)
Nem biztos, hogy a Meteorban ezt fogjuk használni.
